apiVersion: v1
kind: Pod
metadata:
  name: kind-host
  namespace: cvpcp
  labels:
    app: kind-host
spec:
  containers:
    - name: kind-runtime
      image: bodlehg/kind-runtime:test
      imagePullPolicy: Always
      securityContext:
        privileged: true
        capabilities:
          add:
            - NET_RAW
            - NET_ADMIN        
      tty: true
      stdin: true        
      ports:
        - containerPort: 7681
      volumeMounts:
        - name: docker-storage
          mountPath: /var/lib/docker
        - name: cgroup
          mountPath: /sys/fs/cgroup
      resources:
        requests:
          cpu: "4"
          memory: "2Gi"
        limits:
          cpu: "30"
          memory: "20Gi"
  volumes:
    - name: docker-storage
      emptyDir: {}
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup

---

apiVersion: v1
kind: Service
metadata:
  name: kind-terminal-svc
  namespace: cvpcp
spec:
  type: NodePort
  selector:
    app: kind-host
  ports:
    - name: ttyd
      port: 7681
      targetPort: 7681
      nodePort: 21001