apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kind-host-hg-ubuntu
  name: kind-host-hg-ubuntu
  namespace: cvpcp-hg-ubuntu
spec:
  containers:
  - image: bodlehg/kind-runtime:test
    imagePullPolicy: Always
    name: kind-runtime
    ports:
    - containerPort: 7681
    resources:
      limits:
        cpu: '30'
        memory: 20Gi
      requests:
        cpu: '6'
        memory: 4Gi
    securityContext:
      capabilities:
        add:
        - NET_RAW
        - NET_ADMIN
      privileged: true
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /var/lib/docker
      name: docker-storage
    - mountPath: /sys/fs/cgroup
      name: cgroup
  volumes:
  - emptyDir: {}
    name: docker-storage
  - hostPath:
      path: /sys/fs/cgroup
    name: cgroup
---
apiVersion: v1
kind: Service
metadata:
  name: kind-terminal-svc-hg-ubuntu
  namespace: cvpcp-hg-ubuntu
spec:
  ports:
  - name: ttyd
    nodePort: 22174
    port: 7681
    targetPort: 7681
  selector:
    app: kind-host-hg-ubuntu
  type: NodePort
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kind-runtime-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: cvpcp-hg-ubuntu
